// Code generated by ent, DO NOT EDIT.

package job

import (
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldID, id))
}

// GoalID applies equality check predicate on the "goal_id" field. It's identical to GoalIDEQ.
func GoalID(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldGoalID, v))
}

// Stage applies equality check predicate on the "stage" field. It's identical to StageEQ.
func Stage(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStage, v))
}

// AssignedAgent applies equality check predicate on the "assigned_agent" field. It's identical to AssignedAgentEQ.
func AssignedAgent(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAssignedAgent, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldRetryCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// GoalIDEQ applies the EQ predicate on the "goal_id" field.
func GoalIDEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldGoalID, v))
}

// GoalIDNEQ applies the NEQ predicate on the "goal_id" field.
func GoalIDNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldGoalID, v))
}

// GoalIDIn applies the In predicate on the "goal_id" field.
func GoalIDIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldGoalID, vs...))
}

// GoalIDNotIn applies the NotIn predicate on the "goal_id" field.
func GoalIDNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldGoalID, vs...))
}

// GoalIDGT applies the GT predicate on the "goal_id" field.
func GoalIDGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldGoalID, v))
}

// GoalIDGTE applies the GTE predicate on the "goal_id" field.
func GoalIDGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldGoalID, v))
}

// GoalIDLT applies the LT predicate on the "goal_id" field.
func GoalIDLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldGoalID, v))
}

// GoalIDLTE applies the LTE predicate on the "goal_id" field.
func GoalIDLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldGoalID, v))
}

// GoalIDContains applies the Contains predicate on the "goal_id" field.
func GoalIDContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldGoalID, v))
}

// GoalIDHasPrefix applies the HasPrefix predicate on the "goal_id" field.
func GoalIDHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldGoalID, v))
}

// GoalIDHasSuffix applies the HasSuffix predicate on the "goal_id" field.
func GoalIDHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldGoalID, v))
}

// GoalIDEqualFold applies the EqualFold predicate on the "goal_id" field.
func GoalIDEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldGoalID, v))
}

// GoalIDContainsFold applies the ContainsFold predicate on the "goal_id" field.
func GoalIDContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldGoalID, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStage, vs...))
}

// StageGT applies the GT predicate on the "stage" field.
func StageGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStage, v))
}

// StageGTE applies the GTE predicate on the "stage" field.
func StageGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStage, v))
}

// StageLT applies the LT predicate on the "stage" field.
func StageLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStage, v))
}

// StageLTE applies the LTE predicate on the "stage" field.
func StageLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStage, v))
}

// StageContains applies the Contains predicate on the "stage" field.
func StageContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldStage, v))
}

// StageHasPrefix applies the HasPrefix predicate on the "stage" field.
func StageHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldStage, v))
}

// StageHasSuffix applies the HasSuffix predicate on the "stage" field.
func StageHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldStage, v))
}

// StageEqualFold applies the EqualFold predicate on the "stage" field.
func StageEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldStage, v))
}

// StageContainsFold applies the ContainsFold predicate on the "stage" field.
func StageContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldStage, v))
}

// AssignedAgentEQ applies the EQ predicate on the "assigned_agent" field.
func AssignedAgentEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldAssignedAgent, v))
}

// AssignedAgentNEQ applies the NEQ predicate on the "assigned_agent" field.
func AssignedAgentNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldAssignedAgent, v))
}

// AssignedAgentIn applies the In predicate on the "assigned_agent" field.
func AssignedAgentIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldAssignedAgent, vs...))
}

// AssignedAgentNotIn applies the NotIn predicate on the "assigned_agent" field.
func AssignedAgentNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldAssignedAgent, vs...))
}

// AssignedAgentGT applies the GT predicate on the "assigned_agent" field.
func AssignedAgentGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldAssignedAgent, v))
}

// AssignedAgentGTE applies the GTE predicate on the "assigned_agent" field.
func AssignedAgentGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldAssignedAgent, v))
}

// AssignedAgentLT applies the LT predicate on the "assigned_agent" field.
func AssignedAgentLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldAssignedAgent, v))
}

// AssignedAgentLTE applies the LTE predicate on the "assigned_agent" field.
func AssignedAgentLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldAssignedAgent, v))
}

// AssignedAgentContains applies the Contains predicate on the "assigned_agent" field.
func AssignedAgentContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldAssignedAgent, v))
}

// AssignedAgentHasPrefix applies the HasPrefix predicate on the "assigned_agent" field.
func AssignedAgentHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldAssignedAgent, v))
}

// AssignedAgentHasSuffix applies the HasSuffix predicate on the "assigned_agent" field.
func AssignedAgentHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldAssignedAgent, v))
}

// AssignedAgentEqualFold applies the EqualFold predicate on the "assigned_agent" field.
func AssignedAgentEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldAssignedAgent, v))
}

// AssignedAgentContainsFold applies the ContainsFold predicate on the "assigned_agent" field.
func AssignedAgentContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldAssignedAgent, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Job {
	return predicate.Job(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Job {
	return predicate.Job(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Job {
	return predicate.Job(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Job {
	return predicate.Job(sql.FieldContainsFold(FieldStatus, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldRetryCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldCreatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Job {
	return predicate.Job(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Job {
	return predicate.Job(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Job {
	return predicate.Job(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Job {
	return predicate.Job(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Job) predicate.Job {
	return predicate.Job(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Job) predicate.Job {
	return predicate.Job(sql.NotPredicates(p))
}
