// Code generated by ent, DO NOT EDIT.

package memorynode

import (
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldID, id))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldType, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldContent, v))
}

// Importance applies equality check predicate on the "importance" field. It's identical to ImportanceEQ.
func Importance(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldImportance, v))
}

// UsageCount applies equality check predicate on the "usage_count" field. It's identical to UsageCountEQ.
func UsageCount(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldUsageCount, v))
}

// Archived applies equality check predicate on the "archived" field. It's identical to ArchivedEQ.
func Archived(v bool) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldArchived, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldContainsFold(FieldType, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldContainsFold(FieldContent, v))
}

// ImportanceEQ applies the EQ predicate on the "importance" field.
func ImportanceEQ(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldImportance, v))
}

// ImportanceNEQ applies the NEQ predicate on the "importance" field.
func ImportanceNEQ(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldImportance, v))
}

// ImportanceIn applies the In predicate on the "importance" field.
func ImportanceIn(vs ...float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldImportance, vs...))
}

// ImportanceNotIn applies the NotIn predicate on the "importance" field.
func ImportanceNotIn(vs ...float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldImportance, vs...))
}

// ImportanceGT applies the GT predicate on the "importance" field.
func ImportanceGT(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldImportance, v))
}

// ImportanceGTE applies the GTE predicate on the "importance" field.
func ImportanceGTE(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldImportance, v))
}

// ImportanceLT applies the LT predicate on the "importance" field.
func ImportanceLT(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldImportance, v))
}

// ImportanceLTE applies the LTE predicate on the "importance" field.
func ImportanceLTE(v float64) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldImportance, v))
}

// UsageCountEQ applies the EQ predicate on the "usage_count" field.
func UsageCountEQ(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldUsageCount, v))
}

// UsageCountNEQ applies the NEQ predicate on the "usage_count" field.
func UsageCountNEQ(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldUsageCount, v))
}

// UsageCountIn applies the In predicate on the "usage_count" field.
func UsageCountIn(vs ...int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldUsageCount, vs...))
}

// UsageCountNotIn applies the NotIn predicate on the "usage_count" field.
func UsageCountNotIn(vs ...int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldUsageCount, vs...))
}

// UsageCountGT applies the GT predicate on the "usage_count" field.
func UsageCountGT(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldUsageCount, v))
}

// UsageCountGTE applies the GTE predicate on the "usage_count" field.
func UsageCountGTE(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldUsageCount, v))
}

// UsageCountLT applies the LT predicate on the "usage_count" field.
func UsageCountLT(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldUsageCount, v))
}

// UsageCountLTE applies the LTE predicate on the "usage_count" field.
func UsageCountLTE(v int) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldUsageCount, v))
}

// ArchivedEQ applies the EQ predicate on the "archived" field.
func ArchivedEQ(v bool) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldArchived, v))
}

// ArchivedNEQ applies the NEQ predicate on the "archived" field.
func ArchivedNEQ(v bool) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldArchived, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MemoryNode {
	return predicate.MemoryNode(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryNode) predicate.MemoryNode {
	return predicate.MemoryNode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryNode) predicate.MemoryNode {
	return predicate.MemoryNode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryNode) predicate.MemoryNode {
	return predicate.MemoryNode(sql.NotPredicates(p))
}
