// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GoalsColumns holds the columns for the "goals" table.
	GoalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "current_stage", Type: field.TypeString, Default: "OBSERVE"},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "assigned_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GoalsTable holds the schema information for the "goals" table.
	GoalsTable = &schema.Table{
		Name:       "goals",
		Columns:    GoalsColumns,
		PrimaryKey: []*schema.Column{GoalsColumns[0]},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "goal_id", Type: field.TypeString},
		{Name: "stage", Type: field.TypeString},
		{Name: "assigned_agent", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GoalsTable,
		JobsTable,
	}
)

func init() {
}
