// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CodeSymbolsColumns holds the columns for the "code_symbols" table.
	CodeSymbolsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "language", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "line", Type: field.TypeInt},
	}
	// CodeSymbolsTable holds the schema information for the "code_symbols" table.
	CodeSymbolsTable = &schema.Table{
		Name:       "code_symbols",
		Columns:    CodeSymbolsColumns,
		PrimaryKey: []*schema.Column{CodeSymbolsColumns[0]},
	}
	// GoalsColumns holds the columns for the "goals" table.
	GoalsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "current_stage", Type: field.TypeString, Default: "OBSERVE"},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "assigned_agent", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GoalsTable holds the schema information for the "goals" table.
	GoalsTable = &schema.Table{
		Name:       "goals",
		Columns:    GoalsColumns,
		PrimaryKey: []*schema.Column{GoalsColumns[0]},
	}
	// JobsColumns holds the columns for the "jobs" table.
	JobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "goal_id", Type: field.TypeString},
		{Name: "stage", Type: field.TypeString},
		{Name: "assigned_agent", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "PENDING"},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// JobsTable holds the schema information for the "jobs" table.
	JobsTable = &schema.Table{
		Name:       "jobs",
		Columns:    JobsColumns,
		PrimaryKey: []*schema.Column{JobsColumns[0]},
	}
	// MemoryNodesColumns holds the columns for the "memory_nodes" table.
	MemoryNodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "importance", Type: field.TypeFloat64, Default: 0},
		{Name: "usage_count", Type: field.TypeInt, Default: 0},
		{Name: "archived", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MemoryNodesTable holds the schema information for the "memory_nodes" table.
	MemoryNodesTable = &schema.Table{
		Name:       "memory_nodes",
		Columns:    MemoryNodesColumns,
		PrimaryKey: []*schema.Column{MemoryNodesColumns[0]},
	}
	// PatternsColumns holds the columns for the "patterns" table.
	PatternsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Size: 2147483647},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PatternsTable holds the schema information for the "patterns" table.
	PatternsTable = &schema.Table{
		Name:       "patterns",
		Columns:    PatternsColumns,
		PrimaryKey: []*schema.Column{PatternsColumns[0]},
	}
	// WorkspacesColumns holds the columns for the "workspaces" table.
	WorkspacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "path", Type: field.TypeString, Unique: true},
	}
	// WorkspacesTable holds the schema information for the "workspaces" table.
	WorkspacesTable = &schema.Table{
		Name:       "workspaces",
		Columns:    WorkspacesColumns,
		PrimaryKey: []*schema.Column{WorkspacesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CodeSymbolsTable,
		GoalsTable,
		JobsTable,
		MemoryNodesTable,
		PatternsTable,
		WorkspacesTable,
	}
)

func init() {
}
