// Code generated by ent, DO NOT EDIT.

package goal

import (
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldDescription, v))
}

// CurrentStage applies equality check predicate on the "current_stage" field. It's identical to CurrentStageEQ.
func CurrentStage(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCurrentStage, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStatus, v))
}

// AssignedAgent applies equality check predicate on the "assigned_agent" field. It's identical to AssignedAgentEQ.
func AssignedAgent(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldAssignedAgent, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldUpdatedAt, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldDescription, v))
}

// CurrentStageEQ applies the EQ predicate on the "current_stage" field.
func CurrentStageEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCurrentStage, v))
}

// CurrentStageNEQ applies the NEQ predicate on the "current_stage" field.
func CurrentStageNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldCurrentStage, v))
}

// CurrentStageIn applies the In predicate on the "current_stage" field.
func CurrentStageIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldCurrentStage, vs...))
}

// CurrentStageNotIn applies the NotIn predicate on the "current_stage" field.
func CurrentStageNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldCurrentStage, vs...))
}

// CurrentStageGT applies the GT predicate on the "current_stage" field.
func CurrentStageGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldCurrentStage, v))
}

// CurrentStageGTE applies the GTE predicate on the "current_stage" field.
func CurrentStageGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldCurrentStage, v))
}

// CurrentStageLT applies the LT predicate on the "current_stage" field.
func CurrentStageLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldCurrentStage, v))
}

// CurrentStageLTE applies the LTE predicate on the "current_stage" field.
func CurrentStageLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldCurrentStage, v))
}

// CurrentStageContains applies the Contains predicate on the "current_stage" field.
func CurrentStageContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldCurrentStage, v))
}

// CurrentStageHasPrefix applies the HasPrefix predicate on the "current_stage" field.
func CurrentStageHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldCurrentStage, v))
}

// CurrentStageHasSuffix applies the HasSuffix predicate on the "current_stage" field.
func CurrentStageHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldCurrentStage, v))
}

// CurrentStageEqualFold applies the EqualFold predicate on the "current_stage" field.
func CurrentStageEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldCurrentStage, v))
}

// CurrentStageContainsFold applies the ContainsFold predicate on the "current_stage" field.
func CurrentStageContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldCurrentStage, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldStatus, v))
}

// AssignedAgentEQ applies the EQ predicate on the "assigned_agent" field.
func AssignedAgentEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldAssignedAgent, v))
}

// AssignedAgentNEQ applies the NEQ predicate on the "assigned_agent" field.
func AssignedAgentNEQ(v string) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldAssignedAgent, v))
}

// AssignedAgentIn applies the In predicate on the "assigned_agent" field.
func AssignedAgentIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldAssignedAgent, vs...))
}

// AssignedAgentNotIn applies the NotIn predicate on the "assigned_agent" field.
func AssignedAgentNotIn(vs ...string) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldAssignedAgent, vs...))
}

// AssignedAgentGT applies the GT predicate on the "assigned_agent" field.
func AssignedAgentGT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldAssignedAgent, v))
}

// AssignedAgentGTE applies the GTE predicate on the "assigned_agent" field.
func AssignedAgentGTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldAssignedAgent, v))
}

// AssignedAgentLT applies the LT predicate on the "assigned_agent" field.
func AssignedAgentLT(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldAssignedAgent, v))
}

// AssignedAgentLTE applies the LTE predicate on the "assigned_agent" field.
func AssignedAgentLTE(v string) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldAssignedAgent, v))
}

// AssignedAgentContains applies the Contains predicate on the "assigned_agent" field.
func AssignedAgentContains(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContains(FieldAssignedAgent, v))
}

// AssignedAgentHasPrefix applies the HasPrefix predicate on the "assigned_agent" field.
func AssignedAgentHasPrefix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasPrefix(FieldAssignedAgent, v))
}

// AssignedAgentHasSuffix applies the HasSuffix predicate on the "assigned_agent" field.
func AssignedAgentHasSuffix(v string) predicate.Goal {
	return predicate.Goal(sql.FieldHasSuffix(FieldAssignedAgent, v))
}

// AssignedAgentIsNil applies the IsNil predicate on the "assigned_agent" field.
func AssignedAgentIsNil() predicate.Goal {
	return predicate.Goal(sql.FieldIsNull(FieldAssignedAgent))
}

// AssignedAgentNotNil applies the NotNil predicate on the "assigned_agent" field.
func AssignedAgentNotNil() predicate.Goal {
	return predicate.Goal(sql.FieldNotNull(FieldAssignedAgent))
}

// AssignedAgentEqualFold applies the EqualFold predicate on the "assigned_agent" field.
func AssignedAgentEqualFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldEqualFold(FieldAssignedAgent, v))
}

// AssignedAgentContainsFold applies the ContainsFold predicate on the "assigned_agent" field.
func AssignedAgentContainsFold(v string) predicate.Goal {
	return predicate.Goal(sql.FieldContainsFold(FieldAssignedAgent, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Goal {
	return predicate.Goal(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Goal) predicate.Goal {
	return predicate.Goal(sql.NotPredicates(p))
}
