// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"orion/ent/migrate"

	"orion/ent/codesymbol"
	"orion/ent/goal"
	"orion/ent/goalevent"
	"orion/ent/job"
	"orion/ent/memorynode"
	"orion/ent/pattern"
	"orion/ent/workspace"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CodeSymbol is the client for interacting with the CodeSymbol builders.
	CodeSymbol *CodeSymbolClient
	// Goal is the client for interacting with the Goal builders.
	Goal *GoalClient
	// GoalEvent is the client for interacting with the GoalEvent builders.
	GoalEvent *GoalEventClient
	// Job is the client for interacting with the Job builders.
	Job *JobClient
	// MemoryNode is the client for interacting with the MemoryNode builders.
	MemoryNode *MemoryNodeClient
	// Pattern is the client for interacting with the Pattern builders.
	Pattern *PatternClient
	// Workspace is the client for interacting with the Workspace builders.
	Workspace *WorkspaceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CodeSymbol = NewCodeSymbolClient(c.config)
	c.Goal = NewGoalClient(c.config)
	c.GoalEvent = NewGoalEventClient(c.config)
	c.Job = NewJobClient(c.config)
	c.MemoryNode = NewMemoryNodeClient(c.config)
	c.Pattern = NewPatternClient(c.config)
	c.Workspace = NewWorkspaceClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		CodeSymbol: NewCodeSymbolClient(cfg),
		Goal:       NewGoalClient(cfg),
		GoalEvent:  NewGoalEventClient(cfg),
		Job:        NewJobClient(cfg),
		MemoryNode: NewMemoryNodeClient(cfg),
		Pattern:    NewPatternClient(cfg),
		Workspace:  NewWorkspaceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		CodeSymbol: NewCodeSymbolClient(cfg),
		Goal:       NewGoalClient(cfg),
		GoalEvent:  NewGoalEventClient(cfg),
		Job:        NewJobClient(cfg),
		MemoryNode: NewMemoryNodeClient(cfg),
		Pattern:    NewPatternClient(cfg),
		Workspace:  NewWorkspaceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CodeSymbol.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CodeSymbol, c.Goal, c.GoalEvent, c.Job, c.MemoryNode, c.Pattern, c.Workspace,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CodeSymbol, c.Goal, c.GoalEvent, c.Job, c.MemoryNode, c.Pattern, c.Workspace,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CodeSymbolMutation:
		return c.CodeSymbol.mutate(ctx, m)
	case *GoalMutation:
		return c.Goal.mutate(ctx, m)
	case *GoalEventMutation:
		return c.GoalEvent.mutate(ctx, m)
	case *JobMutation:
		return c.Job.mutate(ctx, m)
	case *MemoryNodeMutation:
		return c.MemoryNode.mutate(ctx, m)
	case *PatternMutation:
		return c.Pattern.mutate(ctx, m)
	case *WorkspaceMutation:
		return c.Workspace.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CodeSymbolClient is a client for the CodeSymbol schema.
type CodeSymbolClient struct {
	config
}

// NewCodeSymbolClient returns a client for the CodeSymbol from the given config.
func NewCodeSymbolClient(c config) *CodeSymbolClient {
	return &CodeSymbolClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `codesymbol.Hooks(f(g(h())))`.
func (c *CodeSymbolClient) Use(hooks ...Hook) {
	c.hooks.CodeSymbol = append(c.hooks.CodeSymbol, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `codesymbol.Intercept(f(g(h())))`.
func (c *CodeSymbolClient) Intercept(interceptors ...Interceptor) {
	c.inters.CodeSymbol = append(c.inters.CodeSymbol, interceptors...)
}

// Create returns a builder for creating a CodeSymbol entity.
func (c *CodeSymbolClient) Create() *CodeSymbolCreate {
	mutation := newCodeSymbolMutation(c.config, OpCreate)
	return &CodeSymbolCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CodeSymbol entities.
func (c *CodeSymbolClient) CreateBulk(builders ...*CodeSymbolCreate) *CodeSymbolCreateBulk {
	return &CodeSymbolCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CodeSymbolClient) MapCreateBulk(slice any, setFunc func(*CodeSymbolCreate, int)) *CodeSymbolCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CodeSymbolCreateBulk{err: fmt.Errorf("calling to CodeSymbolClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CodeSymbolCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CodeSymbolCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CodeSymbol.
func (c *CodeSymbolClient) Update() *CodeSymbolUpdate {
	mutation := newCodeSymbolMutation(c.config, OpUpdate)
	return &CodeSymbolUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CodeSymbolClient) UpdateOne(_m *CodeSymbol) *CodeSymbolUpdateOne {
	mutation := newCodeSymbolMutation(c.config, OpUpdateOne, withCodeSymbol(_m))
	return &CodeSymbolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CodeSymbolClient) UpdateOneID(id int) *CodeSymbolUpdateOne {
	mutation := newCodeSymbolMutation(c.config, OpUpdateOne, withCodeSymbolID(id))
	return &CodeSymbolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CodeSymbol.
func (c *CodeSymbolClient) Delete() *CodeSymbolDelete {
	mutation := newCodeSymbolMutation(c.config, OpDelete)
	return &CodeSymbolDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CodeSymbolClient) DeleteOne(_m *CodeSymbol) *CodeSymbolDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CodeSymbolClient) DeleteOneID(id int) *CodeSymbolDeleteOne {
	builder := c.Delete().Where(codesymbol.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CodeSymbolDeleteOne{builder}
}

// Query returns a query builder for CodeSymbol.
func (c *CodeSymbolClient) Query() *CodeSymbolQuery {
	return &CodeSymbolQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCodeSymbol},
		inters: c.Interceptors(),
	}
}

// Get returns a CodeSymbol entity by its id.
func (c *CodeSymbolClient) Get(ctx context.Context, id int) (*CodeSymbol, error) {
	return c.Query().Where(codesymbol.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CodeSymbolClient) GetX(ctx context.Context, id int) *CodeSymbol {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *CodeSymbolClient) Hooks() []Hook {
	return c.hooks.CodeSymbol
}

// Interceptors returns the client interceptors.
func (c *CodeSymbolClient) Interceptors() []Interceptor {
	return c.inters.CodeSymbol
}

func (c *CodeSymbolClient) mutate(ctx context.Context, m *CodeSymbolMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CodeSymbolCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CodeSymbolUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CodeSymbolUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CodeSymbolDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CodeSymbol mutation op: %q", m.Op())
	}
}

// GoalClient is a client for the Goal schema.
type GoalClient struct {
	config
}

// NewGoalClient returns a client for the Goal from the given config.
func NewGoalClient(c config) *GoalClient {
	return &GoalClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `goal.Hooks(f(g(h())))`.
func (c *GoalClient) Use(hooks ...Hook) {
	c.hooks.Goal = append(c.hooks.Goal, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `goal.Intercept(f(g(h())))`.
func (c *GoalClient) Intercept(interceptors ...Interceptor) {
	c.inters.Goal = append(c.inters.Goal, interceptors...)
}

// Create returns a builder for creating a Goal entity.
func (c *GoalClient) Create() *GoalCreate {
	mutation := newGoalMutation(c.config, OpCreate)
	return &GoalCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Goal entities.
func (c *GoalClient) CreateBulk(builders ...*GoalCreate) *GoalCreateBulk {
	return &GoalCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GoalClient) MapCreateBulk(slice any, setFunc func(*GoalCreate, int)) *GoalCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GoalCreateBulk{err: fmt.Errorf("calling to GoalClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GoalCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GoalCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Goal.
func (c *GoalClient) Update() *GoalUpdate {
	mutation := newGoalMutation(c.config, OpUpdate)
	return &GoalUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GoalClient) UpdateOne(_m *Goal) *GoalUpdateOne {
	mutation := newGoalMutation(c.config, OpUpdateOne, withGoal(_m))
	return &GoalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GoalClient) UpdateOneID(id string) *GoalUpdateOne {
	mutation := newGoalMutation(c.config, OpUpdateOne, withGoalID(id))
	return &GoalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Goal.
func (c *GoalClient) Delete() *GoalDelete {
	mutation := newGoalMutation(c.config, OpDelete)
	return &GoalDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GoalClient) DeleteOne(_m *Goal) *GoalDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GoalClient) DeleteOneID(id string) *GoalDeleteOne {
	builder := c.Delete().Where(goal.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GoalDeleteOne{builder}
}

// Query returns a query builder for Goal.
func (c *GoalClient) Query() *GoalQuery {
	return &GoalQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGoal},
		inters: c.Interceptors(),
	}
}

// Get returns a Goal entity by its id.
func (c *GoalClient) Get(ctx context.Context, id string) (*Goal, error) {
	return c.Query().Where(goal.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GoalClient) GetX(ctx context.Context, id string) *Goal {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEvents queries the events edge of a Goal.
func (c *GoalClient) QueryEvents(_m *Goal) *GoalEventQuery {
	query := (&GoalEventClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(goal.Table, goal.FieldID, id),
			sqlgraph.To(goalevent.Table, goalevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, goal.EventsTable, goal.EventsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GoalClient) Hooks() []Hook {
	return c.hooks.Goal
}

// Interceptors returns the client interceptors.
func (c *GoalClient) Interceptors() []Interceptor {
	return c.inters.Goal
}

func (c *GoalClient) mutate(ctx context.Context, m *GoalMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GoalCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GoalUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GoalUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GoalDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Goal mutation op: %q", m.Op())
	}
}

// GoalEventClient is a client for the GoalEvent schema.
type GoalEventClient struct {
	config
}

// NewGoalEventClient returns a client for the GoalEvent from the given config.
func NewGoalEventClient(c config) *GoalEventClient {
	return &GoalEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `goalevent.Hooks(f(g(h())))`.
func (c *GoalEventClient) Use(hooks ...Hook) {
	c.hooks.GoalEvent = append(c.hooks.GoalEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `goalevent.Intercept(f(g(h())))`.
func (c *GoalEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.GoalEvent = append(c.inters.GoalEvent, interceptors...)
}

// Create returns a builder for creating a GoalEvent entity.
func (c *GoalEventClient) Create() *GoalEventCreate {
	mutation := newGoalEventMutation(c.config, OpCreate)
	return &GoalEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of GoalEvent entities.
func (c *GoalEventClient) CreateBulk(builders ...*GoalEventCreate) *GoalEventCreateBulk {
	return &GoalEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GoalEventClient) MapCreateBulk(slice any, setFunc func(*GoalEventCreate, int)) *GoalEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GoalEventCreateBulk{err: fmt.Errorf("calling to GoalEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GoalEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GoalEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for GoalEvent.
func (c *GoalEventClient) Update() *GoalEventUpdate {
	mutation := newGoalEventMutation(c.config, OpUpdate)
	return &GoalEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GoalEventClient) UpdateOne(_m *GoalEvent) *GoalEventUpdateOne {
	mutation := newGoalEventMutation(c.config, OpUpdateOne, withGoalEvent(_m))
	return &GoalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GoalEventClient) UpdateOneID(id int) *GoalEventUpdateOne {
	mutation := newGoalEventMutation(c.config, OpUpdateOne, withGoalEventID(id))
	return &GoalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for GoalEvent.
func (c *GoalEventClient) Delete() *GoalEventDelete {
	mutation := newGoalEventMutation(c.config, OpDelete)
	return &GoalEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GoalEventClient) DeleteOne(_m *GoalEvent) *GoalEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GoalEventClient) DeleteOneID(id int) *GoalEventDeleteOne {
	builder := c.Delete().Where(goalevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GoalEventDeleteOne{builder}
}

// Query returns a query builder for GoalEvent.
func (c *GoalEventClient) Query() *GoalEventQuery {
	return &GoalEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGoalEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a GoalEvent entity by its id.
func (c *GoalEventClient) Get(ctx context.Context, id int) (*GoalEvent, error) {
	return c.Query().Where(goalevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GoalEventClient) GetX(ctx context.Context, id int) *GoalEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryGoal queries the goal edge of a GoalEvent.
func (c *GoalEventClient) QueryGoal(_m *GoalEvent) *GoalQuery {
	query := (&GoalClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(goalevent.Table, goalevent.FieldID, id),
			sqlgraph.To(goal.Table, goal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goalevent.GoalTable, goalevent.GoalColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GoalEventClient) Hooks() []Hook {
	return c.hooks.GoalEvent
}

// Interceptors returns the client interceptors.
func (c *GoalEventClient) Interceptors() []Interceptor {
	return c.inters.GoalEvent
}

func (c *GoalEventClient) mutate(ctx context.Context, m *GoalEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GoalEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GoalEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GoalEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GoalEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown GoalEvent mutation op: %q", m.Op())
	}
}

// JobClient is a client for the Job schema.
type JobClient struct {
	config
}

// NewJobClient returns a client for the Job from the given config.
func NewJobClient(c config) *JobClient {
	return &JobClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `job.Hooks(f(g(h())))`.
func (c *JobClient) Use(hooks ...Hook) {
	c.hooks.Job = append(c.hooks.Job, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `job.Intercept(f(g(h())))`.
func (c *JobClient) Intercept(interceptors ...Interceptor) {
	c.inters.Job = append(c.inters.Job, interceptors...)
}

// Create returns a builder for creating a Job entity.
func (c *JobClient) Create() *JobCreate {
	mutation := newJobMutation(c.config, OpCreate)
	return &JobCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Job entities.
func (c *JobClient) CreateBulk(builders ...*JobCreate) *JobCreateBulk {
	return &JobCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *JobClient) MapCreateBulk(slice any, setFunc func(*JobCreate, int)) *JobCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &JobCreateBulk{err: fmt.Errorf("calling to JobClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*JobCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &JobCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Job.
func (c *JobClient) Update() *JobUpdate {
	mutation := newJobMutation(c.config, OpUpdate)
	return &JobUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *JobClient) UpdateOne(_m *Job) *JobUpdateOne {
	mutation := newJobMutation(c.config, OpUpdateOne, withJob(_m))
	return &JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *JobClient) UpdateOneID(id string) *JobUpdateOne {
	mutation := newJobMutation(c.config, OpUpdateOne, withJobID(id))
	return &JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Job.
func (c *JobClient) Delete() *JobDelete {
	mutation := newJobMutation(c.config, OpDelete)
	return &JobDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *JobClient) DeleteOne(_m *Job) *JobDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *JobClient) DeleteOneID(id string) *JobDeleteOne {
	builder := c.Delete().Where(job.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &JobDeleteOne{builder}
}

// Query returns a query builder for Job.
func (c *JobClient) Query() *JobQuery {
	return &JobQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeJob},
		inters: c.Interceptors(),
	}
}

// Get returns a Job entity by its id.
func (c *JobClient) Get(ctx context.Context, id string) (*Job, error) {
	return c.Query().Where(job.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *JobClient) GetX(ctx context.Context, id string) *Job {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *JobClient) Hooks() []Hook {
	return c.hooks.Job
}

// Interceptors returns the client interceptors.
func (c *JobClient) Interceptors() []Interceptor {
	return c.inters.Job
}

func (c *JobClient) mutate(ctx context.Context, m *JobMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&JobCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&JobUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&JobUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&JobDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Job mutation op: %q", m.Op())
	}
}

// MemoryNodeClient is a client for the MemoryNode schema.
type MemoryNodeClient struct {
	config
}

// NewMemoryNodeClient returns a client for the MemoryNode from the given config.
func NewMemoryNodeClient(c config) *MemoryNodeClient {
	return &MemoryNodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `memorynode.Hooks(f(g(h())))`.
func (c *MemoryNodeClient) Use(hooks ...Hook) {
	c.hooks.MemoryNode = append(c.hooks.MemoryNode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `memorynode.Intercept(f(g(h())))`.
func (c *MemoryNodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.MemoryNode = append(c.inters.MemoryNode, interceptors...)
}

// Create returns a builder for creating a MemoryNode entity.
func (c *MemoryNodeClient) Create() *MemoryNodeCreate {
	mutation := newMemoryNodeMutation(c.config, OpCreate)
	return &MemoryNodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MemoryNode entities.
func (c *MemoryNodeClient) CreateBulk(builders ...*MemoryNodeCreate) *MemoryNodeCreateBulk {
	return &MemoryNodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MemoryNodeClient) MapCreateBulk(slice any, setFunc func(*MemoryNodeCreate, int)) *MemoryNodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MemoryNodeCreateBulk{err: fmt.Errorf("calling to MemoryNodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MemoryNodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MemoryNodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MemoryNode.
func (c *MemoryNodeClient) Update() *MemoryNodeUpdate {
	mutation := newMemoryNodeMutation(c.config, OpUpdate)
	return &MemoryNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MemoryNodeClient) UpdateOne(_m *MemoryNode) *MemoryNodeUpdateOne {
	mutation := newMemoryNodeMutation(c.config, OpUpdateOne, withMemoryNode(_m))
	return &MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MemoryNodeClient) UpdateOneID(id int) *MemoryNodeUpdateOne {
	mutation := newMemoryNodeMutation(c.config, OpUpdateOne, withMemoryNodeID(id))
	return &MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MemoryNode.
func (c *MemoryNodeClient) Delete() *MemoryNodeDelete {
	mutation := newMemoryNodeMutation(c.config, OpDelete)
	return &MemoryNodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MemoryNodeClient) DeleteOne(_m *MemoryNode) *MemoryNodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MemoryNodeClient) DeleteOneID(id int) *MemoryNodeDeleteOne {
	builder := c.Delete().Where(memorynode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MemoryNodeDeleteOne{builder}
}

// Query returns a query builder for MemoryNode.
func (c *MemoryNodeClient) Query() *MemoryNodeQuery {
	return &MemoryNodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMemoryNode},
		inters: c.Interceptors(),
	}
}

// Get returns a MemoryNode entity by its id.
func (c *MemoryNodeClient) Get(ctx context.Context, id int) (*MemoryNode, error) {
	return c.Query().Where(memorynode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MemoryNodeClient) GetX(ctx context.Context, id int) *MemoryNode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MemoryNodeClient) Hooks() []Hook {
	return c.hooks.MemoryNode
}

// Interceptors returns the client interceptors.
func (c *MemoryNodeClient) Interceptors() []Interceptor {
	return c.inters.MemoryNode
}

func (c *MemoryNodeClient) mutate(ctx context.Context, m *MemoryNodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MemoryNodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MemoryNodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MemoryNodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MemoryNodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MemoryNode mutation op: %q", m.Op())
	}
}

// PatternClient is a client for the Pattern schema.
type PatternClient struct {
	config
}

// NewPatternClient returns a client for the Pattern from the given config.
func NewPatternClient(c config) *PatternClient {
	return &PatternClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pattern.Hooks(f(g(h())))`.
func (c *PatternClient) Use(hooks ...Hook) {
	c.hooks.Pattern = append(c.hooks.Pattern, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pattern.Intercept(f(g(h())))`.
func (c *PatternClient) Intercept(interceptors ...Interceptor) {
	c.inters.Pattern = append(c.inters.Pattern, interceptors...)
}

// Create returns a builder for creating a Pattern entity.
func (c *PatternClient) Create() *PatternCreate {
	mutation := newPatternMutation(c.config, OpCreate)
	return &PatternCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Pattern entities.
func (c *PatternClient) CreateBulk(builders ...*PatternCreate) *PatternCreateBulk {
	return &PatternCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PatternClient) MapCreateBulk(slice any, setFunc func(*PatternCreate, int)) *PatternCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PatternCreateBulk{err: fmt.Errorf("calling to PatternClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PatternCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PatternCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Pattern.
func (c *PatternClient) Update() *PatternUpdate {
	mutation := newPatternMutation(c.config, OpUpdate)
	return &PatternUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PatternClient) UpdateOne(_m *Pattern) *PatternUpdateOne {
	mutation := newPatternMutation(c.config, OpUpdateOne, withPattern(_m))
	return &PatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PatternClient) UpdateOneID(id int) *PatternUpdateOne {
	mutation := newPatternMutation(c.config, OpUpdateOne, withPatternID(id))
	return &PatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Pattern.
func (c *PatternClient) Delete() *PatternDelete {
	mutation := newPatternMutation(c.config, OpDelete)
	return &PatternDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PatternClient) DeleteOne(_m *Pattern) *PatternDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PatternClient) DeleteOneID(id int) *PatternDeleteOne {
	builder := c.Delete().Where(pattern.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PatternDeleteOne{builder}
}

// Query returns a query builder for Pattern.
func (c *PatternClient) Query() *PatternQuery {
	return &PatternQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePattern},
		inters: c.Interceptors(),
	}
}

// Get returns a Pattern entity by its id.
func (c *PatternClient) Get(ctx context.Context, id int) (*Pattern, error) {
	return c.Query().Where(pattern.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PatternClient) GetX(ctx context.Context, id int) *Pattern {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PatternClient) Hooks() []Hook {
	return c.hooks.Pattern
}

// Interceptors returns the client interceptors.
func (c *PatternClient) Interceptors() []Interceptor {
	return c.inters.Pattern
}

func (c *PatternClient) mutate(ctx context.Context, m *PatternMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PatternCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PatternUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PatternUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PatternDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Pattern mutation op: %q", m.Op())
	}
}

// WorkspaceClient is a client for the Workspace schema.
type WorkspaceClient struct {
	config
}

// NewWorkspaceClient returns a client for the Workspace from the given config.
func NewWorkspaceClient(c config) *WorkspaceClient {
	return &WorkspaceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `workspace.Hooks(f(g(h())))`.
func (c *WorkspaceClient) Use(hooks ...Hook) {
	c.hooks.Workspace = append(c.hooks.Workspace, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `workspace.Intercept(f(g(h())))`.
func (c *WorkspaceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Workspace = append(c.inters.Workspace, interceptors...)
}

// Create returns a builder for creating a Workspace entity.
func (c *WorkspaceClient) Create() *WorkspaceCreate {
	mutation := newWorkspaceMutation(c.config, OpCreate)
	return &WorkspaceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Workspace entities.
func (c *WorkspaceClient) CreateBulk(builders ...*WorkspaceCreate) *WorkspaceCreateBulk {
	return &WorkspaceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *WorkspaceClient) MapCreateBulk(slice any, setFunc func(*WorkspaceCreate, int)) *WorkspaceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &WorkspaceCreateBulk{err: fmt.Errorf("calling to WorkspaceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*WorkspaceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &WorkspaceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Workspace.
func (c *WorkspaceClient) Update() *WorkspaceUpdate {
	mutation := newWorkspaceMutation(c.config, OpUpdate)
	return &WorkspaceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *WorkspaceClient) UpdateOne(_m *Workspace) *WorkspaceUpdateOne {
	mutation := newWorkspaceMutation(c.config, OpUpdateOne, withWorkspace(_m))
	return &WorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *WorkspaceClient) UpdateOneID(id int) *WorkspaceUpdateOne {
	mutation := newWorkspaceMutation(c.config, OpUpdateOne, withWorkspaceID(id))
	return &WorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Workspace.
func (c *WorkspaceClient) Delete() *WorkspaceDelete {
	mutation := newWorkspaceMutation(c.config, OpDelete)
	return &WorkspaceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *WorkspaceClient) DeleteOne(_m *Workspace) *WorkspaceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *WorkspaceClient) DeleteOneID(id int) *WorkspaceDeleteOne {
	builder := c.Delete().Where(workspace.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &WorkspaceDeleteOne{builder}
}

// Query returns a query builder for Workspace.
func (c *WorkspaceClient) Query() *WorkspaceQuery {
	return &WorkspaceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeWorkspace},
		inters: c.Interceptors(),
	}
}

// Get returns a Workspace entity by its id.
func (c *WorkspaceClient) Get(ctx context.Context, id int) (*Workspace, error) {
	return c.Query().Where(workspace.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *WorkspaceClient) GetX(ctx context.Context, id int) *Workspace {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *WorkspaceClient) Hooks() []Hook {
	return c.hooks.Workspace
}

// Interceptors returns the client interceptors.
func (c *WorkspaceClient) Interceptors() []Interceptor {
	return c.inters.Workspace
}

func (c *WorkspaceClient) mutate(ctx context.Context, m *WorkspaceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&WorkspaceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&WorkspaceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&WorkspaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&WorkspaceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Workspace mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CodeSymbol, Goal, GoalEvent, Job, MemoryNode, Pattern, Workspace []ent.Hook
	}
	inters struct {
		CodeSymbol, Goal, GoalEvent, Job, MemoryNode, Pattern,
		Workspace []ent.Interceptor
	}
)
