// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/codesymbol"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodeSymbolCreate is the builder for creating a CodeSymbol entity.
type CodeSymbolCreate struct {
	config
	mutation *CodeSymbolMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CodeSymbolCreate) SetName(v string) *CodeSymbolCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *CodeSymbolCreate) SetKind(v string) *CodeSymbolCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *CodeSymbolCreate) SetLanguage(v string) *CodeSymbolCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *CodeSymbolCreate) SetPath(v string) *CodeSymbolCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetLine sets the "line" field.
func (_c *CodeSymbolCreate) SetLine(v int) *CodeSymbolCreate {
	_c.mutation.SetLine(v)
	return _c
}

// Mutation returns the CodeSymbolMutation object of the builder.
func (_c *CodeSymbolCreate) Mutation() *CodeSymbolMutation {
	return _c.mutation
}

// Save creates the CodeSymbol in the database.
func (_c *CodeSymbolCreate) Save(ctx context.Context) (*CodeSymbol, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodeSymbolCreate) SaveX(ctx context.Context) *CodeSymbol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodeSymbolCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodeSymbolCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodeSymbolCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CodeSymbol.name"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "CodeSymbol.kind"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "CodeSymbol.language"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "CodeSymbol.path"`)}
	}
	if _, ok := _c.mutation.Line(); !ok {
		return &ValidationError{Name: "line", err: errors.New(`ent: missing required field "CodeSymbol.line"`)}
	}
	return nil
}

func (_c *CodeSymbolCreate) sqlSave(ctx context.Context) (*CodeSymbol, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodeSymbolCreate) createSpec() (*CodeSymbol, *sqlgraph.CreateSpec) {
	var (
		_node = &CodeSymbol{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codesymbol.Table, sqlgraph.NewFieldSpec(codesymbol.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(codesymbol.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(codesymbol.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(codesymbol.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(codesymbol.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Line(); ok {
		_spec.SetField(codesymbol.FieldLine, field.TypeInt, value)
		_node.Line = value
	}
	return _node, _spec
}

// CodeSymbolCreateBulk is the builder for creating many CodeSymbol entities in bulk.
type CodeSymbolCreateBulk struct {
	config
	err      error
	builders []*CodeSymbolCreate
}

// Save creates the CodeSymbol entities in the database.
func (_c *CodeSymbolCreateBulk) Save(ctx context.Context) ([]*CodeSymbol, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodeSymbol, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodeSymbolMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodeSymbolCreateBulk) SaveX(ctx context.Context) []*CodeSymbol {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodeSymbolCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodeSymbolCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
