// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"orion/ent/codesymbol"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CodeSymbol is the model entity for the CodeSymbol schema.
type CodeSymbol struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Path holds the value of the "path" field.
	Path string `json:"path,omitempty"`
	// Line holds the value of the "line" field.
	Line         int `json:"line,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodeSymbol) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codesymbol.FieldID, codesymbol.FieldLine:
			values[i] = new(sql.NullInt64)
		case codesymbol.FieldName, codesymbol.FieldKind, codesymbol.FieldLanguage, codesymbol.FieldPath:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodeSymbol fields.
func (_m *CodeSymbol) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codesymbol.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case codesymbol.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case codesymbol.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case codesymbol.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case codesymbol.FieldPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field path", values[i])
			} else if value.Valid {
				_m.Path = value.String
			}
		case codesymbol.FieldLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field line", values[i])
			} else if value.Valid {
				_m.Line = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodeSymbol.
// This includes values selected through modifiers, order, etc.
func (_m *CodeSymbol) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CodeSymbol.
// Note that you need to call CodeSymbol.Unwrap() before calling this method if this CodeSymbol
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodeSymbol) Update() *CodeSymbolUpdateOne {
	return NewCodeSymbolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodeSymbol entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodeSymbol) Unwrap() *CodeSymbol {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodeSymbol is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodeSymbol) String() string {
	var builder strings.Builder
	builder.WriteString("CodeSymbol(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("path=")
	builder.WriteString(_m.Path)
	builder.WriteString(", ")
	builder.WriteString("line=")
	builder.WriteString(fmt.Sprintf("%v", _m.Line))
	builder.WriteByte(')')
	return builder.String()
}

// CodeSymbols is a parsable slice of CodeSymbol.
type CodeSymbols []*CodeSymbol
