// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/codesymbol"
	"orion/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodeSymbolUpdate is the builder for updating CodeSymbol entities.
type CodeSymbolUpdate struct {
	config
	hooks    []Hook
	mutation *CodeSymbolMutation
}

// Where appends a list predicates to the CodeSymbolUpdate builder.
func (_u *CodeSymbolUpdate) Where(ps ...predicate.CodeSymbol) *CodeSymbolUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CodeSymbolUpdate) SetName(v string) *CodeSymbolUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodeSymbolUpdate) SetNillableName(v *string) *CodeSymbolUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *CodeSymbolUpdate) SetKind(v string) *CodeSymbolUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CodeSymbolUpdate) SetNillableKind(v *string) *CodeSymbolUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *CodeSymbolUpdate) SetLanguage(v string) *CodeSymbolUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *CodeSymbolUpdate) SetNillableLanguage(v *string) *CodeSymbolUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *CodeSymbolUpdate) SetPath(v string) *CodeSymbolUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *CodeSymbolUpdate) SetNillablePath(v *string) *CodeSymbolUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetLine sets the "line" field.
func (_u *CodeSymbolUpdate) SetLine(v int) *CodeSymbolUpdate {
	_u.mutation.ResetLine()
	_u.mutation.SetLine(v)
	return _u
}

// SetNillableLine sets the "line" field if the given value is not nil.
func (_u *CodeSymbolUpdate) SetNillableLine(v *int) *CodeSymbolUpdate {
	if v != nil {
		_u.SetLine(*v)
	}
	return _u
}

// AddLine adds value to the "line" field.
func (_u *CodeSymbolUpdate) AddLine(v int) *CodeSymbolUpdate {
	_u.mutation.AddLine(v)
	return _u
}

// Mutation returns the CodeSymbolMutation object of the builder.
func (_u *CodeSymbolUpdate) Mutation() *CodeSymbolMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodeSymbolUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeSymbolUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodeSymbolUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeSymbolUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodeSymbolUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(codesymbol.Table, codesymbol.Columns, sqlgraph.NewFieldSpec(codesymbol.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codesymbol.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(codesymbol.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(codesymbol.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(codesymbol.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Line(); ok {
		_spec.SetField(codesymbol.FieldLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLine(); ok {
		_spec.AddField(codesymbol.FieldLine, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codesymbol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodeSymbolUpdateOne is the builder for updating a single CodeSymbol entity.
type CodeSymbolUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodeSymbolMutation
}

// SetName sets the "name" field.
func (_u *CodeSymbolUpdateOne) SetName(v string) *CodeSymbolUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodeSymbolUpdateOne) SetNillableName(v *string) *CodeSymbolUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *CodeSymbolUpdateOne) SetKind(v string) *CodeSymbolUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *CodeSymbolUpdateOne) SetNillableKind(v *string) *CodeSymbolUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *CodeSymbolUpdateOne) SetLanguage(v string) *CodeSymbolUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *CodeSymbolUpdateOne) SetNillableLanguage(v *string) *CodeSymbolUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *CodeSymbolUpdateOne) SetPath(v string) *CodeSymbolUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *CodeSymbolUpdateOne) SetNillablePath(v *string) *CodeSymbolUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetLine sets the "line" field.
func (_u *CodeSymbolUpdateOne) SetLine(v int) *CodeSymbolUpdateOne {
	_u.mutation.ResetLine()
	_u.mutation.SetLine(v)
	return _u
}

// SetNillableLine sets the "line" field if the given value is not nil.
func (_u *CodeSymbolUpdateOne) SetNillableLine(v *int) *CodeSymbolUpdateOne {
	if v != nil {
		_u.SetLine(*v)
	}
	return _u
}

// AddLine adds value to the "line" field.
func (_u *CodeSymbolUpdateOne) AddLine(v int) *CodeSymbolUpdateOne {
	_u.mutation.AddLine(v)
	return _u
}

// Mutation returns the CodeSymbolMutation object of the builder.
func (_u *CodeSymbolUpdateOne) Mutation() *CodeSymbolMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodeSymbolUpdate builder.
func (_u *CodeSymbolUpdateOne) Where(ps ...predicate.CodeSymbol) *CodeSymbolUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodeSymbolUpdateOne) Select(field string, fields ...string) *CodeSymbolUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodeSymbol entity.
func (_u *CodeSymbolUpdateOne) Save(ctx context.Context) (*CodeSymbol, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodeSymbolUpdateOne) SaveX(ctx context.Context) *CodeSymbol {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodeSymbolUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodeSymbolUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodeSymbolUpdateOne) sqlSave(ctx context.Context) (_node *CodeSymbol, err error) {
	_spec := sqlgraph.NewUpdateSpec(codesymbol.Table, codesymbol.Columns, sqlgraph.NewFieldSpec(codesymbol.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodeSymbol.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codesymbol.FieldID)
		for _, f := range fields {
			if !codesymbol.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codesymbol.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codesymbol.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(codesymbol.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(codesymbol.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(codesymbol.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Line(); ok {
		_spec.SetField(codesymbol.FieldLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLine(); ok {
		_spec.AddField(codesymbol.FieldLine, field.TypeInt, value)
	}
	_node = &CodeSymbol{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codesymbol.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
