// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"orion/ent/goal"
	"orion/ent/goalevent"
	"orion/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalEventQuery is the builder for querying GoalEvent entities.
type GoalEventQuery struct {
	config
	ctx        *QueryContext
	order      []goalevent.OrderOption
	inters     []Interceptor
	predicates []predicate.GoalEvent
	withGoal   *GoalQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoalEventQuery builder.
func (_q *GoalEventQuery) Where(ps ...predicate.GoalEvent) *GoalEventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GoalEventQuery) Limit(limit int) *GoalEventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GoalEventQuery) Offset(offset int) *GoalEventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GoalEventQuery) Unique(unique bool) *GoalEventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GoalEventQuery) Order(o ...goalevent.OrderOption) *GoalEventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryGoal chains the current query on the "goal" edge.
func (_q *GoalEventQuery) QueryGoal() *GoalQuery {
	query := (&GoalClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goalevent.Table, goalevent.FieldID, selector),
			sqlgraph.To(goal.Table, goal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, goalevent.GoalTable, goalevent.GoalColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GoalEvent entity from the query.
// Returns a *NotFoundError when no GoalEvent was found.
func (_q *GoalEventQuery) First(ctx context.Context) (*GoalEvent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goalevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GoalEventQuery) FirstX(ctx context.Context) *GoalEvent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GoalEvent ID from the query.
// Returns a *NotFoundError when no GoalEvent ID was found.
func (_q *GoalEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goalevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GoalEventQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GoalEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GoalEvent entity is found.
// Returns a *NotFoundError when no GoalEvent entities are found.
func (_q *GoalEventQuery) Only(ctx context.Context) (*GoalEvent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goalevent.Label}
	default:
		return nil, &NotSingularError{goalevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GoalEventQuery) OnlyX(ctx context.Context) *GoalEvent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GoalEvent ID in the query.
// Returns a *NotSingularError when more than one GoalEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GoalEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goalevent.Label}
	default:
		err = &NotSingularError{goalevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GoalEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GoalEvents.
func (_q *GoalEventQuery) All(ctx context.Context) ([]*GoalEvent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GoalEvent, *GoalEventQuery]()
	return withInterceptors[[]*GoalEvent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GoalEventQuery) AllX(ctx context.Context) []*GoalEvent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GoalEvent IDs.
func (_q *GoalEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(goalevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GoalEventQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GoalEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GoalEventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GoalEventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GoalEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GoalEventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoalEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GoalEventQuery) Clone() *GoalEventQuery {
	if _q == nil {
		return nil
	}
	return &GoalEventQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]goalevent.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.GoalEvent{}, _q.predicates...),
		withGoal:   _q.withGoal.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithGoal tells the query-builder to eager-load the nodes that are connected to
// the "goal" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GoalEventQuery) WithGoal(opts ...func(*GoalQuery)) *GoalEventQuery {
	query := (&GoalClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGoal = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GoalEvent.Query().
//		GroupBy(goalevent.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GoalEventQuery) GroupBy(field string, fields ...string) *GoalEventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoalEventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = goalevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.GoalEvent.Query().
//		Select(goalevent.FieldType).
//		Scan(ctx, &v)
func (_q *GoalEventQuery) Select(fields ...string) *GoalEventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GoalEventSelect{GoalEventQuery: _q}
	sbuild.label = goalevent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoalEventSelect configured with the given aggregations.
func (_q *GoalEventQuery) Aggregate(fns ...AggregateFunc) *GoalEventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GoalEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !goalevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GoalEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GoalEvent, error) {
	var (
		nodes       = []*GoalEvent{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withGoal != nil,
		}
	)
	if _q.withGoal != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, goalevent.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GoalEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GoalEvent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withGoal; query != nil {
		if err := _q.loadGoal(ctx, query, nodes, nil,
			func(n *GoalEvent, e *Goal) { n.Edges.Goal = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GoalEventQuery) loadGoal(ctx context.Context, query *GoalQuery, nodes []*GoalEvent, init func(*GoalEvent), assign func(*GoalEvent, *Goal)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*GoalEvent)
	for i := range nodes {
		if nodes[i].goal_events == nil {
			continue
		}
		fk := *nodes[i].goal_events
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(goal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "goal_events" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GoalEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GoalEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(goalevent.Table, goalevent.Columns, sqlgraph.NewFieldSpec(goalevent.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalevent.FieldID)
		for i := range fields {
			if fields[i] != goalevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GoalEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(goalevent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = goalevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GoalEventGroupBy is the group-by builder for GoalEvent entities.
type GoalEventGroupBy struct {
	selector
	build *GoalEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GoalEventGroupBy) Aggregate(fns ...AggregateFunc) *GoalEventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GoalEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalEventQuery, *GoalEventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GoalEventGroupBy) sqlScan(ctx context.Context, root *GoalEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoalEventSelect is the builder for selecting fields of GoalEvent entities.
type GoalEventSelect struct {
	*GoalEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GoalEventSelect) Aggregate(fns ...AggregateFunc) *GoalEventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GoalEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalEventQuery, *GoalEventSelect](ctx, _s.GoalEventQuery, _s, _s.inters, v)
}

func (_s *GoalEventSelect) sqlScan(ctx context.Context, root *GoalEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
