// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"orion/ent/goal"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Goal is the model entity for the Goal schema.
type Goal struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CurrentStage holds the value of the "current_stage" field.
	CurrentStage string `json:"current_stage,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AssignedAgent holds the value of the "assigned_agent" field.
	AssignedAgent string `json:"assigned_agent,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoalQuery when eager-loading is set.
	Edges        GoalEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GoalEdges holds the relations/edges for other nodes in the graph.
type GoalEdges struct {
	// Events holds the value of the events edge.
	Events []*GoalEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e GoalEdges) EventsOrErr() ([]*GoalEvent, error) {
	if e.loadedTypes[0] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Goal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goal.FieldID, goal.FieldDescription, goal.FieldCurrentStage, goal.FieldStatus, goal.FieldAssignedAgent:
			values[i] = new(sql.NullString)
		case goal.FieldCreatedAt, goal.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Goal fields.
func (_m *Goal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goal.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case goal.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case goal.FieldCurrentStage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_stage", values[i])
			} else if value.Valid {
				_m.CurrentStage = value.String
			}
		case goal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case goal.FieldAssignedAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_agent", values[i])
			} else if value.Valid {
				_m.AssignedAgent = value.String
			}
		case goal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goal.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Goal.
// This includes values selected through modifiers, order, etc.
func (_m *Goal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvents queries the "events" edge of the Goal entity.
func (_m *Goal) QueryEvents() *GoalEventQuery {
	return NewGoalClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this Goal.
// Note that you need to call Goal.Unwrap() before calling this method if this Goal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Goal) Update() *GoalUpdateOne {
	return NewGoalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Goal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Goal) Unwrap() *Goal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Goal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Goal) String() string {
	var builder strings.Builder
	builder.WriteString("Goal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("current_stage=")
	builder.WriteString(_m.CurrentStage)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("assigned_agent=")
	builder.WriteString(_m.AssignedAgent)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Goals is a parsable slice of Goal.
type Goals []*Goal
