// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/goal"
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalUpdate is the builder for updating Goal entities.
type GoalUpdate struct {
	config
	hooks    []Hook
	mutation *GoalMutation
}

// Where appends a list predicates to the GoalUpdate builder.
func (_u *GoalUpdate) Where(ps ...predicate.Goal) *GoalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *GoalUpdate) SetDescription(v string) *GoalUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableDescription(v *string) *GoalUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCurrentStage sets the "current_stage" field.
func (_u *GoalUpdate) SetCurrentStage(v string) *GoalUpdate {
	_u.mutation.SetCurrentStage(v)
	return _u
}

// SetNillableCurrentStage sets the "current_stage" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableCurrentStage(v *string) *GoalUpdate {
	if v != nil {
		_u.SetCurrentStage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoalUpdate) SetStatus(v string) *GoalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableStatus(v *string) *GoalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAssignedAgent sets the "assigned_agent" field.
func (_u *GoalUpdate) SetAssignedAgent(v string) *GoalUpdate {
	_u.mutation.SetAssignedAgent(v)
	return _u
}

// SetNillableAssignedAgent sets the "assigned_agent" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableAssignedAgent(v *string) *GoalUpdate {
	if v != nil {
		_u.SetAssignedAgent(*v)
	}
	return _u
}

// ClearAssignedAgent clears the value of the "assigned_agent" field.
func (_u *GoalUpdate) ClearAssignedAgent() *GoalUpdate {
	_u.mutation.ClearAssignedAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalUpdate) SetCreatedAt(v time.Time) *GoalUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalUpdate) SetNillableCreatedAt(v *time.Time) *GoalUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalUpdate) SetUpdatedAt(v time.Time) *GoalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GoalMutation object of the builder.
func (_u *GoalUpdate) Mutation() *GoalMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GoalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(goal.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStage(); ok {
		_spec.SetField(goal.FieldCurrentStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(goal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAgent(); ok {
		_spec.SetField(goal.FieldAssignedAgent, field.TypeString, value)
	}
	if _u.mutation.AssignedAgentCleared() {
		_spec.ClearField(goal.FieldAssignedAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goal.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoalUpdateOne is the builder for updating a single Goal entity.
type GoalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalMutation
}

// SetDescription sets the "description" field.
func (_u *GoalUpdateOne) SetDescription(v string) *GoalUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableDescription(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCurrentStage sets the "current_stage" field.
func (_u *GoalUpdateOne) SetCurrentStage(v string) *GoalUpdateOne {
	_u.mutation.SetCurrentStage(v)
	return _u
}

// SetNillableCurrentStage sets the "current_stage" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableCurrentStage(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetCurrentStage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GoalUpdateOne) SetStatus(v string) *GoalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableStatus(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAssignedAgent sets the "assigned_agent" field.
func (_u *GoalUpdateOne) SetAssignedAgent(v string) *GoalUpdateOne {
	_u.mutation.SetAssignedAgent(v)
	return _u
}

// SetNillableAssignedAgent sets the "assigned_agent" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableAssignedAgent(v *string) *GoalUpdateOne {
	if v != nil {
		_u.SetAssignedAgent(*v)
	}
	return _u
}

// ClearAssignedAgent clears the value of the "assigned_agent" field.
func (_u *GoalUpdateOne) ClearAssignedAgent() *GoalUpdateOne {
	_u.mutation.ClearAssignedAgent()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalUpdateOne) SetCreatedAt(v time.Time) *GoalUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalUpdateOne) SetNillableCreatedAt(v *time.Time) *GoalUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GoalUpdateOne) SetUpdatedAt(v time.Time) *GoalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GoalMutation object of the builder.
func (_u *GoalUpdateOne) Mutation() *GoalMutation {
	return _u.mutation
}

// Where appends a list predicates to the GoalUpdate builder.
func (_u *GoalUpdateOne) Where(ps ...predicate.Goal) *GoalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoalUpdateOne) Select(field string, fields ...string) *GoalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Goal entity.
func (_u *GoalUpdateOne) Save(ctx context.Context) (*Goal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalUpdateOne) SaveX(ctx context.Context) *Goal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GoalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := goal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GoalUpdateOne) sqlSave(ctx context.Context) (_node *Goal, err error) {
	_spec := sqlgraph.NewUpdateSpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Goal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goal.FieldID)
		for _, f := range fields {
			if !goal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(goal.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStage(); ok {
		_spec.SetField(goal.FieldCurrentStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(goal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAgent(); ok {
		_spec.SetField(goal.FieldAssignedAgent, field.TypeString, value)
	}
	if _u.mutation.AssignedAgentCleared() {
		_spec.ClearField(goal.FieldAssignedAgent, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(goal.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Goal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
