// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/goal"
	"orion/ent/goalevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalEventCreate is the builder for creating a GoalEvent entity.
type GoalEventCreate struct {
	config
	mutation *GoalEventMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *GoalEventCreate) SetType(v string) *GoalEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *GoalEventCreate) SetPayload(v map[string]interface{}) *GoalEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoalEventCreate) SetCreatedAt(v time.Time) *GoalEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoalEventCreate) SetNillableCreatedAt(v *time.Time) *GoalEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetGoalID sets the "goal" edge to the Goal entity by ID.
func (_c *GoalEventCreate) SetGoalID(id string) *GoalEventCreate {
	_c.mutation.SetGoalID(id)
	return _c
}

// SetNillableGoalID sets the "goal" edge to the Goal entity by ID if the given value is not nil.
func (_c *GoalEventCreate) SetNillableGoalID(id *string) *GoalEventCreate {
	if id != nil {
		_c = _c.SetGoalID(*id)
	}
	return _c
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_c *GoalEventCreate) SetGoal(v *Goal) *GoalEventCreate {
	return _c.SetGoalID(v.ID)
}

// Mutation returns the GoalEventMutation object of the builder.
func (_c *GoalEventCreate) Mutation() *GoalEventMutation {
	return _c.mutation
}

// Save creates the GoalEvent in the database.
func (_c *GoalEventCreate) Save(ctx context.Context) (*GoalEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoalEventCreate) SaveX(ctx context.Context) *GoalEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoalEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := goalevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoalEventCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "GoalEvent.type"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "GoalEvent.payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GoalEvent.created_at"`)}
	}
	return nil
}

func (_c *GoalEventCreate) sqlSave(ctx context.Context) (*GoalEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoalEventCreate) createSpec() (*GoalEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &GoalEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goalevent.Table, sqlgraph.NewFieldSpec(goalevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(goalevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(goalevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(goalevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalevent.GoalTable,
			Columns: []string{goalevent.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.goal_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GoalEventCreateBulk is the builder for creating many GoalEvent entities in bulk.
type GoalEventCreateBulk struct {
	config
	err      error
	builders []*GoalEventCreate
}

// Save creates the GoalEvent entities in the database.
func (_c *GoalEventCreateBulk) Save(ctx context.Context) ([]*GoalEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GoalEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoalEventCreateBulk) SaveX(ctx context.Context) []*GoalEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
