// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/goal"
	"orion/ent/goalevent"
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalEventUpdate is the builder for updating GoalEvent entities.
type GoalEventUpdate struct {
	config
	hooks    []Hook
	mutation *GoalEventMutation
}

// Where appends a list predicates to the GoalEventUpdate builder.
func (_u *GoalEventUpdate) Where(ps ...predicate.GoalEvent) *GoalEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *GoalEventUpdate) SetType(v string) *GoalEventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GoalEventUpdate) SetNillableType(v *string) *GoalEventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *GoalEventUpdate) SetPayload(v map[string]interface{}) *GoalEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalEventUpdate) SetCreatedAt(v time.Time) *GoalEventUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalEventUpdate) SetNillableCreatedAt(v *time.Time) *GoalEventUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGoalID sets the "goal" edge to the Goal entity by ID.
func (_u *GoalEventUpdate) SetGoalID(id string) *GoalEventUpdate {
	_u.mutation.SetGoalID(id)
	return _u
}

// SetNillableGoalID sets the "goal" edge to the Goal entity by ID if the given value is not nil.
func (_u *GoalEventUpdate) SetNillableGoalID(id *string) *GoalEventUpdate {
	if id != nil {
		_u = _u.SetGoalID(*id)
	}
	return _u
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_u *GoalEventUpdate) SetGoal(v *Goal) *GoalEventUpdate {
	return _u.SetGoalID(v.ID)
}

// Mutation returns the GoalEventMutation object of the builder.
func (_u *GoalEventUpdate) Mutation() *GoalEventMutation {
	return _u.mutation
}

// ClearGoal clears the "goal" edge to the Goal entity.
func (_u *GoalEventUpdate) ClearGoal() *GoalEventUpdate {
	_u.mutation.ClearGoal()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GoalEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GoalEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoalEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(goalevent.Table, goalevent.Columns, sqlgraph.NewFieldSpec(goalevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(goalevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(goalevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goalevent.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GoalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalevent.GoalTable,
			Columns: []string{goalevent.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalevent.GoalTable,
			Columns: []string{goalevent.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GoalEventUpdateOne is the builder for updating a single GoalEvent entity.
type GoalEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GoalEventMutation
}

// SetType sets the "type" field.
func (_u *GoalEventUpdateOne) SetType(v string) *GoalEventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *GoalEventUpdateOne) SetNillableType(v *string) *GoalEventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *GoalEventUpdateOne) SetPayload(v map[string]interface{}) *GoalEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GoalEventUpdateOne) SetCreatedAt(v time.Time) *GoalEventUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GoalEventUpdateOne) SetNillableCreatedAt(v *time.Time) *GoalEventUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetGoalID sets the "goal" edge to the Goal entity by ID.
func (_u *GoalEventUpdateOne) SetGoalID(id string) *GoalEventUpdateOne {
	_u.mutation.SetGoalID(id)
	return _u
}

// SetNillableGoalID sets the "goal" edge to the Goal entity by ID if the given value is not nil.
func (_u *GoalEventUpdateOne) SetNillableGoalID(id *string) *GoalEventUpdateOne {
	if id != nil {
		_u = _u.SetGoalID(*id)
	}
	return _u
}

// SetGoal sets the "goal" edge to the Goal entity.
func (_u *GoalEventUpdateOne) SetGoal(v *Goal) *GoalEventUpdateOne {
	return _u.SetGoalID(v.ID)
}

// Mutation returns the GoalEventMutation object of the builder.
func (_u *GoalEventUpdateOne) Mutation() *GoalEventMutation {
	return _u.mutation
}

// ClearGoal clears the "goal" edge to the Goal entity.
func (_u *GoalEventUpdateOne) ClearGoal() *GoalEventUpdateOne {
	_u.mutation.ClearGoal()
	return _u
}

// Where appends a list predicates to the GoalEventUpdate builder.
func (_u *GoalEventUpdateOne) Where(ps ...predicate.GoalEvent) *GoalEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GoalEventUpdateOne) Select(field string, fields ...string) *GoalEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GoalEvent entity.
func (_u *GoalEventUpdateOne) Save(ctx context.Context) (*GoalEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GoalEventUpdateOne) SaveX(ctx context.Context) *GoalEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GoalEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GoalEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *GoalEventUpdateOne) sqlSave(ctx context.Context) (_node *GoalEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(goalevent.Table, goalevent.Columns, sqlgraph.NewFieldSpec(goalevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GoalEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goalevent.FieldID)
		for _, f := range fields {
			if !goalevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != goalevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(goalevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(goalevent.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(goalevent.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.GoalCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalevent.GoalTable,
			Columns: []string{goalevent.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GoalIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   goalevent.GoalTable,
			Columns: []string{goalevent.GoalColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GoalEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{goalevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
