// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/goal"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GoalCreate is the builder for creating a Goal entity.
type GoalCreate struct {
	config
	mutation *GoalMutation
	hooks    []Hook
}

// SetDescription sets the "description" field.
func (_c *GoalCreate) SetDescription(v string) *GoalCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetCurrentStage sets the "current_stage" field.
func (_c *GoalCreate) SetCurrentStage(v string) *GoalCreate {
	_c.mutation.SetCurrentStage(v)
	return _c
}

// SetNillableCurrentStage sets the "current_stage" field if the given value is not nil.
func (_c *GoalCreate) SetNillableCurrentStage(v *string) *GoalCreate {
	if v != nil {
		_c.SetCurrentStage(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *GoalCreate) SetStatus(v string) *GoalCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GoalCreate) SetNillableStatus(v *string) *GoalCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAssignedAgent sets the "assigned_agent" field.
func (_c *GoalCreate) SetAssignedAgent(v string) *GoalCreate {
	_c.mutation.SetAssignedAgent(v)
	return _c
}

// SetNillableAssignedAgent sets the "assigned_agent" field if the given value is not nil.
func (_c *GoalCreate) SetNillableAssignedAgent(v *string) *GoalCreate {
	if v != nil {
		_c.SetAssignedAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GoalCreate) SetCreatedAt(v time.Time) *GoalCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GoalCreate) SetNillableCreatedAt(v *time.Time) *GoalCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GoalCreate) SetUpdatedAt(v time.Time) *GoalCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GoalCreate) SetNillableUpdatedAt(v *time.Time) *GoalCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GoalCreate) SetID(v string) *GoalCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GoalMutation object of the builder.
func (_c *GoalCreate) Mutation() *GoalMutation {
	return _c.mutation
}

// Save creates the Goal in the database.
func (_c *GoalCreate) Save(ctx context.Context) (*Goal, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GoalCreate) SaveX(ctx context.Context) *Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GoalCreate) defaults() {
	if _, ok := _c.mutation.CurrentStage(); !ok {
		v := goal.DefaultCurrentStage
		_c.mutation.SetCurrentStage(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := goal.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := goal.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := goal.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GoalCreate) check() error {
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Goal.description"`)}
	}
	if _, ok := _c.mutation.CurrentStage(); !ok {
		return &ValidationError{Name: "current_stage", err: errors.New(`ent: missing required field "Goal.current_stage"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Goal.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Goal.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Goal.updated_at"`)}
	}
	return nil
}

func (_c *GoalCreate) sqlSave(ctx context.Context) (*Goal, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Goal.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GoalCreate) createSpec() (*Goal, *sqlgraph.CreateSpec) {
	var (
		_node = &Goal{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(goal.Table, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(goal.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CurrentStage(); ok {
		_spec.SetField(goal.FieldCurrentStage, field.TypeString, value)
		_node.CurrentStage = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(goal.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AssignedAgent(); ok {
		_spec.SetField(goal.FieldAssignedAgent, field.TypeString, value)
		_node.AssignedAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(goal.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(goal.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GoalCreateBulk is the builder for creating many Goal entities in bulk.
type GoalCreateBulk struct {
	config
	err      error
	builders []*GoalCreate
}

// Save creates the Goal entities in the database.
func (_c *GoalCreateBulk) Save(ctx context.Context) ([]*Goal, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Goal, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GoalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GoalCreateBulk) SaveX(ctx context.Context) []*Goal {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GoalCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GoalCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
