// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"orion/ent/goal"
	"orion/ent/goalevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GoalEvent is the model entity for the GoalEvent schema.
type GoalEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GoalEventQuery when eager-loading is set.
	Edges        GoalEventEdges `json:"edges"`
	goal_events  *string
	selectValues sql.SelectValues
}

// GoalEventEdges holds the relations/edges for other nodes in the graph.
type GoalEventEdges struct {
	// Goal holds the value of the goal edge.
	Goal *Goal `json:"goal,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GoalOrErr returns the Goal value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GoalEventEdges) GoalOrErr() (*Goal, error) {
	if e.Goal != nil {
		return e.Goal, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: goal.Label}
	}
	return nil, &NotLoadedError{edge: "goal"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GoalEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case goalevent.FieldPayload:
			values[i] = new([]byte)
		case goalevent.FieldID:
			values[i] = new(sql.NullInt64)
		case goalevent.FieldType:
			values[i] = new(sql.NullString)
		case goalevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case goalevent.ForeignKeys[0]: // goal_events
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GoalEvent fields.
func (_m *GoalEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case goalevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case goalevent.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case goalevent.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case goalevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case goalevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field goal_events", values[i])
			} else if value.Valid {
				_m.goal_events = new(string)
				*_m.goal_events = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GoalEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GoalEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGoal queries the "goal" edge of the GoalEvent entity.
func (_m *GoalEvent) QueryGoal() *GoalQuery {
	return NewGoalEventClient(_m.config).QueryGoal(_m)
}

// Update returns a builder for updating this GoalEvent.
// Note that you need to call GoalEvent.Unwrap() before calling this method if this GoalEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GoalEvent) Update() *GoalEventUpdateOne {
	return NewGoalEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GoalEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GoalEvent) Unwrap() *GoalEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GoalEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GoalEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GoalEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GoalEvents is a parsable slice of GoalEvent.
type GoalEvents []*GoalEvent
