// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/job"
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGoalID sets the "goal_id" field.
func (_u *JobUpdate) SetGoalID(v string) *JobUpdate {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *JobUpdate) SetNillableGoalID(v *string) *JobUpdate {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *JobUpdate) SetStage(v string) *JobUpdate {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStage(v *string) *JobUpdate {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetAssignedAgent sets the "assigned_agent" field.
func (_u *JobUpdate) SetAssignedAgent(v string) *JobUpdate {
	_u.mutation.SetAssignedAgent(v)
	return _u
}

// SetNillableAssignedAgent sets the "assigned_agent" field if the given value is not nil.
func (_u *JobUpdate) SetNillableAssignedAgent(v *string) *JobUpdate {
	if v != nil {
		_u.SetAssignedAgent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdate) SetStatus(v string) *JobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdate) SetNillableStatus(v *string) *JobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *JobUpdate) SetRetryCount(v int) *JobUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *JobUpdate) SetNillableRetryCount(v *int) *JobUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *JobUpdate) AddRetryCount(v int) *JobUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JobUpdate) SetCreatedAt(v time.Time) *JobUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableCreatedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdate) SetFinishedAt(v time.Time) *JobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableFinishedAt(v *time.Time) *JobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdate) ClearFinishedAt() *JobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(job.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(job.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAgent(); ok {
		_spec.SetField(job.FieldAssignedAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(job.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(job.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetGoalID sets the "goal_id" field.
func (_u *JobUpdateOne) SetGoalID(v string) *JobUpdateOne {
	_u.mutation.SetGoalID(v)
	return _u
}

// SetNillableGoalID sets the "goal_id" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableGoalID(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetGoalID(*v)
	}
	return _u
}

// SetStage sets the "stage" field.
func (_u *JobUpdateOne) SetStage(v string) *JobUpdateOne {
	_u.mutation.SetStage(v)
	return _u
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStage(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStage(*v)
	}
	return _u
}

// SetAssignedAgent sets the "assigned_agent" field.
func (_u *JobUpdateOne) SetAssignedAgent(v string) *JobUpdateOne {
	_u.mutation.SetAssignedAgent(v)
	return _u
}

// SetNillableAssignedAgent sets the "assigned_agent" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableAssignedAgent(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetAssignedAgent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *JobUpdateOne) SetStatus(v string) *JobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableStatus(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *JobUpdateOne) SetRetryCount(v int) *JobUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableRetryCount(v *int) *JobUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *JobUpdateOne) AddRetryCount(v int) *JobUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JobUpdateOne) SetCreatedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableCreatedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *JobUpdateOne) SetFinishedAt(v time.Time) *JobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableFinishedAt(v *time.Time) *JobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *JobUpdateOne) ClearFinishedAt() *JobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GoalID(); ok {
		_spec.SetField(job.FieldGoalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Stage(); ok {
		_spec.SetField(job.FieldStage, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssignedAgent(); ok {
		_spec.SetField(job.FieldAssignedAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(job.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(job.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(job.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(job.FieldFinishedAt, field.TypeTime)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
