// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/memorynode"
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeUpdate is the builder for updating MemoryNode entities.
type MemoryNodeUpdate struct {
	config
	hooks    []Hook
	mutation *MemoryNodeMutation
}

// Where appends a list predicates to the MemoryNodeUpdate builder.
func (_u *MemoryNodeUpdate) Where(ps ...predicate.MemoryNode) *MemoryNodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *MemoryNodeUpdate) SetType(v string) *MemoryNodeUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableType(v *string) *MemoryNodeUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryNodeUpdate) SetContent(v string) *MemoryNodeUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableContent(v *string) *MemoryNodeUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetImportance sets the "importance" field.
func (_u *MemoryNodeUpdate) SetImportance(v float64) *MemoryNodeUpdate {
	_u.mutation.ResetImportance()
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableImportance(v *float64) *MemoryNodeUpdate {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// AddImportance adds value to the "importance" field.
func (_u *MemoryNodeUpdate) AddImportance(v float64) *MemoryNodeUpdate {
	_u.mutation.AddImportance(v)
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *MemoryNodeUpdate) SetUsageCount(v int) *MemoryNodeUpdate {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableUsageCount(v *int) *MemoryNodeUpdate {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *MemoryNodeUpdate) AddUsageCount(v int) *MemoryNodeUpdate {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetArchived sets the "archived" field.
func (_u *MemoryNodeUpdate) SetArchived(v bool) *MemoryNodeUpdate {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableArchived(v *bool) *MemoryNodeUpdate {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemoryNodeUpdate) SetCreatedAt(v time.Time) *MemoryNodeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemoryNodeUpdate) SetNillableCreatedAt(v *time.Time) *MemoryNodeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryNodeUpdate) SetUpdatedAt(v time.Time) *MemoryNodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_u *MemoryNodeUpdate) Mutation() *MemoryNodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemoryNodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryNodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemoryNodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryNodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryNodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memorynode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MemoryNodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(memorynode.Table, memorynode.Columns, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(memorynode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memorynode.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(memorynode.FieldImportance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImportance(); ok {
		_spec.AddField(memorynode.FieldImportance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(memorynode.FieldUsageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(memorynode.FieldUsageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(memorynode.FieldArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memorynode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memorynode.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemoryNodeUpdateOne is the builder for updating a single MemoryNode entity.
type MemoryNodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemoryNodeMutation
}

// SetType sets the "type" field.
func (_u *MemoryNodeUpdateOne) SetType(v string) *MemoryNodeUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableType(v *string) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *MemoryNodeUpdateOne) SetContent(v string) *MemoryNodeUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableContent(v *string) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetImportance sets the "importance" field.
func (_u *MemoryNodeUpdateOne) SetImportance(v float64) *MemoryNodeUpdateOne {
	_u.mutation.ResetImportance()
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableImportance(v *float64) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// AddImportance adds value to the "importance" field.
func (_u *MemoryNodeUpdateOne) AddImportance(v float64) *MemoryNodeUpdateOne {
	_u.mutation.AddImportance(v)
	return _u
}

// SetUsageCount sets the "usage_count" field.
func (_u *MemoryNodeUpdateOne) SetUsageCount(v int) *MemoryNodeUpdateOne {
	_u.mutation.ResetUsageCount()
	_u.mutation.SetUsageCount(v)
	return _u
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableUsageCount(v *int) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetUsageCount(*v)
	}
	return _u
}

// AddUsageCount adds value to the "usage_count" field.
func (_u *MemoryNodeUpdateOne) AddUsageCount(v int) *MemoryNodeUpdateOne {
	_u.mutation.AddUsageCount(v)
	return _u
}

// SetArchived sets the "archived" field.
func (_u *MemoryNodeUpdateOne) SetArchived(v bool) *MemoryNodeUpdateOne {
	_u.mutation.SetArchived(v)
	return _u
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableArchived(v *bool) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetArchived(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MemoryNodeUpdateOne) SetCreatedAt(v time.Time) *MemoryNodeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MemoryNodeUpdateOne) SetNillableCreatedAt(v *time.Time) *MemoryNodeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MemoryNodeUpdateOne) SetUpdatedAt(v time.Time) *MemoryNodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_u *MemoryNodeUpdateOne) Mutation() *MemoryNodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the MemoryNodeUpdate builder.
func (_u *MemoryNodeUpdateOne) Where(ps ...predicate.MemoryNode) *MemoryNodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemoryNodeUpdateOne) Select(field string, fields ...string) *MemoryNodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemoryNode entity.
func (_u *MemoryNodeUpdateOne) Save(ctx context.Context) (*MemoryNode, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemoryNodeUpdateOne) SaveX(ctx context.Context) *MemoryNode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemoryNodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemoryNodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MemoryNodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := memorynode.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *MemoryNodeUpdateOne) sqlSave(ctx context.Context) (_node *MemoryNode, err error) {
	_spec := sqlgraph.NewUpdateSpec(memorynode.Table, memorynode.Columns, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemoryNode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memorynode.FieldID)
		for _, f := range fields {
			if !memorynode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memorynode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(memorynode.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(memorynode.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(memorynode.FieldImportance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedImportance(); ok {
		_spec.AddField(memorynode.FieldImportance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UsageCount(); ok {
		_spec.SetField(memorynode.FieldUsageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageCount(); ok {
		_spec.AddField(memorynode.FieldUsageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Archived(); ok {
		_spec.SetField(memorynode.FieldArchived, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(memorynode.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(memorynode.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MemoryNode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorynode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
