// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/memorynode"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeCreate is the builder for creating a MemoryNode entity.
type MemoryNodeCreate struct {
	config
	mutation *MemoryNodeMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *MemoryNodeCreate) SetType(v string) *MemoryNodeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *MemoryNodeCreate) SetContent(v string) *MemoryNodeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetImportance sets the "importance" field.
func (_c *MemoryNodeCreate) SetImportance(v float64) *MemoryNodeCreate {
	_c.mutation.SetImportance(v)
	return _c
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableImportance(v *float64) *MemoryNodeCreate {
	if v != nil {
		_c.SetImportance(*v)
	}
	return _c
}

// SetUsageCount sets the "usage_count" field.
func (_c *MemoryNodeCreate) SetUsageCount(v int) *MemoryNodeCreate {
	_c.mutation.SetUsageCount(v)
	return _c
}

// SetNillableUsageCount sets the "usage_count" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableUsageCount(v *int) *MemoryNodeCreate {
	if v != nil {
		_c.SetUsageCount(*v)
	}
	return _c
}

// SetArchived sets the "archived" field.
func (_c *MemoryNodeCreate) SetArchived(v bool) *MemoryNodeCreate {
	_c.mutation.SetArchived(v)
	return _c
}

// SetNillableArchived sets the "archived" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableArchived(v *bool) *MemoryNodeCreate {
	if v != nil {
		_c.SetArchived(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemoryNodeCreate) SetCreatedAt(v time.Time) *MemoryNodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableCreatedAt(v *time.Time) *MemoryNodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MemoryNodeCreate) SetUpdatedAt(v time.Time) *MemoryNodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MemoryNodeCreate) SetNillableUpdatedAt(v *time.Time) *MemoryNodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the MemoryNodeMutation object of the builder.
func (_c *MemoryNodeCreate) Mutation() *MemoryNodeMutation {
	return _c.mutation
}

// Save creates the MemoryNode in the database.
func (_c *MemoryNodeCreate) Save(ctx context.Context) (*MemoryNode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemoryNodeCreate) SaveX(ctx context.Context) *MemoryNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemoryNodeCreate) defaults() {
	if _, ok := _c.mutation.Importance(); !ok {
		v := memorynode.DefaultImportance
		_c.mutation.SetImportance(v)
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		v := memorynode.DefaultUsageCount
		_c.mutation.SetUsageCount(v)
	}
	if _, ok := _c.mutation.Archived(); !ok {
		v := memorynode.DefaultArchived
		_c.mutation.SetArchived(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memorynode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := memorynode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemoryNodeCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "MemoryNode.type"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "MemoryNode.content"`)}
	}
	if _, ok := _c.mutation.Importance(); !ok {
		return &ValidationError{Name: "importance", err: errors.New(`ent: missing required field "MemoryNode.importance"`)}
	}
	if _, ok := _c.mutation.UsageCount(); !ok {
		return &ValidationError{Name: "usage_count", err: errors.New(`ent: missing required field "MemoryNode.usage_count"`)}
	}
	if _, ok := _c.mutation.Archived(); !ok {
		return &ValidationError{Name: "archived", err: errors.New(`ent: missing required field "MemoryNode.archived"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MemoryNode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MemoryNode.updated_at"`)}
	}
	return nil
}

func (_c *MemoryNodeCreate) sqlSave(ctx context.Context) (*MemoryNode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemoryNodeCreate) createSpec() (*MemoryNode, *sqlgraph.CreateSpec) {
	var (
		_node = &MemoryNode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memorynode.Table, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(memorynode.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(memorynode.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Importance(); ok {
		_spec.SetField(memorynode.FieldImportance, field.TypeFloat64, value)
		_node.Importance = value
	}
	if value, ok := _c.mutation.UsageCount(); ok {
		_spec.SetField(memorynode.FieldUsageCount, field.TypeInt, value)
		_node.UsageCount = value
	}
	if value, ok := _c.mutation.Archived(); ok {
		_spec.SetField(memorynode.FieldArchived, field.TypeBool, value)
		_node.Archived = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memorynode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(memorynode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// MemoryNodeCreateBulk is the builder for creating many MemoryNode entities in bulk.
type MemoryNodeCreateBulk struct {
	config
	err      error
	builders []*MemoryNodeCreate
}

// Save creates the MemoryNode entities in the database.
func (_c *MemoryNodeCreateBulk) Save(ctx context.Context) ([]*MemoryNode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemoryNode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemoryNodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemoryNodeCreateBulk) SaveX(ctx context.Context) []*MemoryNode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemoryNodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemoryNodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
