// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"orion/ent/memorynode"
	"orion/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemoryNodeDelete is the builder for deleting a MemoryNode entity.
type MemoryNodeDelete struct {
	config
	hooks    []Hook
	mutation *MemoryNodeMutation
}

// Where appends a list predicates to the MemoryNodeDelete builder.
func (_d *MemoryNodeDelete) Where(ps ...predicate.MemoryNode) *MemoryNodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemoryNodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryNodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemoryNodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memorynode.Table, sqlgraph.NewFieldSpec(memorynode.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemoryNodeDeleteOne is the builder for deleting a single MemoryNode entity.
type MemoryNodeDeleteOne struct {
	_d *MemoryNodeDelete
}

// Where appends a list predicates to the MemoryNodeDelete builder.
func (_d *MemoryNodeDeleteOne) Where(ps ...predicate.MemoryNode) *MemoryNodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemoryNodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memorynode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemoryNodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
