// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orion/ent/pattern"
	"orion/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PatternUpdate is the builder for updating Pattern entities.
type PatternUpdate struct {
	config
	hooks    []Hook
	mutation *PatternMutation
}

// Where appends a list predicates to the PatternUpdate builder.
func (_u *PatternUpdate) Where(ps ...predicate.Pattern) *PatternUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PatternUpdate) SetName(v string) *PatternUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PatternUpdate) SetNillableName(v *string) *PatternUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PatternUpdate) SetDescription(v string) *PatternUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PatternUpdate) SetNillableDescription(v *string) *PatternUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PatternUpdate) SetMetadata(v map[string]interface{}) *PatternUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PatternUpdate) SetCreatedAt(v time.Time) *PatternUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PatternUpdate) SetNillableCreatedAt(v *time.Time) *PatternUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PatternMutation object of the builder.
func (_u *PatternUpdate) Mutation() *PatternMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PatternUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatternUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PatternUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatternUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PatternUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pattern.Table, pattern.Columns, sqlgraph.NewFieldSpec(pattern.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pattern.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pattern.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(pattern.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pattern.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PatternUpdateOne is the builder for updating a single Pattern entity.
type PatternUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PatternMutation
}

// SetName sets the "name" field.
func (_u *PatternUpdateOne) SetName(v string) *PatternUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PatternUpdateOne) SetNillableName(v *string) *PatternUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PatternUpdateOne) SetDescription(v string) *PatternUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PatternUpdateOne) SetNillableDescription(v *string) *PatternUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *PatternUpdateOne) SetMetadata(v map[string]interface{}) *PatternUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PatternUpdateOne) SetCreatedAt(v time.Time) *PatternUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PatternUpdateOne) SetNillableCreatedAt(v *time.Time) *PatternUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PatternMutation object of the builder.
func (_u *PatternUpdateOne) Mutation() *PatternMutation {
	return _u.mutation
}

// Where appends a list predicates to the PatternUpdate builder.
func (_u *PatternUpdateOne) Where(ps ...predicate.Pattern) *PatternUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PatternUpdateOne) Select(field string, fields ...string) *PatternUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Pattern entity.
func (_u *PatternUpdateOne) Save(ctx context.Context) (*Pattern, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatternUpdateOne) SaveX(ctx context.Context) *Pattern {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PatternUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatternUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PatternUpdateOne) sqlSave(ctx context.Context) (_node *Pattern, err error) {
	_spec := sqlgraph.NewUpdateSpec(pattern.Table, pattern.Columns, sqlgraph.NewFieldSpec(pattern.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Pattern.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pattern.FieldID)
		for _, f := range fields {
			if !pattern.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pattern.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pattern.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pattern.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(pattern.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pattern.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Pattern{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pattern.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
