// Code generated by ent, DO NOT EDIT.

package ent

import (
	"orion/ent/goal"
	"orion/ent/job"
	"orion/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	goalFields := schema.Goal{}.Fields()
	_ = goalFields
	// goalDescCurrentStage is the schema descriptor for current_stage field.
	goalDescCurrentStage := goalFields[2].Descriptor()
	// goal.DefaultCurrentStage holds the default value on creation for the current_stage field.
	goal.DefaultCurrentStage = goalDescCurrentStage.Default.(string)
	// goalDescStatus is the schema descriptor for status field.
	goalDescStatus := goalFields[3].Descriptor()
	// goal.DefaultStatus holds the default value on creation for the status field.
	goal.DefaultStatus = goalDescStatus.Default.(string)
	// goalDescCreatedAt is the schema descriptor for created_at field.
	goalDescCreatedAt := goalFields[5].Descriptor()
	// goal.DefaultCreatedAt holds the default value on creation for the created_at field.
	goal.DefaultCreatedAt = goalDescCreatedAt.Default.(func() time.Time)
	// goalDescUpdatedAt is the schema descriptor for updated_at field.
	goalDescUpdatedAt := goalFields[6].Descriptor()
	// goal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	goal.DefaultUpdatedAt = goalDescUpdatedAt.Default.(func() time.Time)
	// goal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	goal.UpdateDefaultUpdatedAt = goalDescUpdatedAt.UpdateDefault.(func() time.Time)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescStatus is the schema descriptor for status field.
	jobDescStatus := jobFields[4].Descriptor()
	// job.DefaultStatus holds the default value on creation for the status field.
	job.DefaultStatus = jobDescStatus.Default.(string)
	// jobDescRetryCount is the schema descriptor for retry_count field.
	jobDescRetryCount := jobFields[5].Descriptor()
	// job.DefaultRetryCount holds the default value on creation for the retry_count field.
	job.DefaultRetryCount = jobDescRetryCount.Default.(int)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[6].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
}
