// Code generated by ent, DO NOT EDIT.

package goalevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the goalevent type in the database.
	Label = "goal_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeGoal holds the string denoting the goal edge name in mutations.
	EdgeGoal = "goal"
	// Table holds the table name of the goalevent in the database.
	Table = "goal_events"
	// GoalTable is the table that holds the goal relation/edge.
	GoalTable = "goal_events"
	// GoalInverseTable is the table name for the Goal entity.
	// It exists in this package in order to avoid circular dependency with the "goal" package.
	GoalInverseTable = "goals"
	// GoalColumn is the table column denoting the goal relation/edge.
	GoalColumn = "goal_events"
)

// Columns holds all SQL columns for goalevent fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldPayload,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "goal_events"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"goal_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the GoalEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByGoalField orders the results by goal field.
func ByGoalField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGoalStep(), sql.OrderByField(field, opts...))
	}
}
func newGoalStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GoalInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GoalTable, GoalColumn),
	)
}
