// Code generated by ent, DO NOT EDIT.

package codesymbol

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the codesymbol type in the database.
	Label = "code_symbol"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldLine holds the string denoting the line field in the database.
	FieldLine = "line"
	// Table holds the table name of the codesymbol in the database.
	Table = "code_symbols"
)

// Columns holds all SQL columns for codesymbol fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldKind,
	FieldLanguage,
	FieldPath,
	FieldLine,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the CodeSymbol queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByLine orders the results by the line field.
func ByLine(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLine, opts...).ToFunc()
}
