// Code generated by ent, DO NOT EDIT.

package codesymbol

import (
	"orion/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldName, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldKind, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldLanguage, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldPath, v))
}

// Line applies equality check predicate on the "line" field. It's identical to LineEQ.
func Line(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldLine, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContainsFold(FieldName, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContainsFold(FieldKind, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContainsFold(FieldLanguage, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldContainsFold(FieldPath, v))
}

// LineEQ applies the EQ predicate on the "line" field.
func LineEQ(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldEQ(FieldLine, v))
}

// LineNEQ applies the NEQ predicate on the "line" field.
func LineNEQ(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNEQ(FieldLine, v))
}

// LineIn applies the In predicate on the "line" field.
func LineIn(vs ...int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldIn(FieldLine, vs...))
}

// LineNotIn applies the NotIn predicate on the "line" field.
func LineNotIn(vs ...int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldNotIn(FieldLine, vs...))
}

// LineGT applies the GT predicate on the "line" field.
func LineGT(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGT(FieldLine, v))
}

// LineGTE applies the GTE predicate on the "line" field.
func LineGTE(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldGTE(FieldLine, v))
}

// LineLT applies the LT predicate on the "line" field.
func LineLT(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLT(FieldLine, v))
}

// LineLTE applies the LTE predicate on the "line" field.
func LineLTE(v int) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.FieldLTE(FieldLine, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodeSymbol) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodeSymbol) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodeSymbol) predicate.CodeSymbol {
	return predicate.CodeSymbol(sql.NotPredicates(p))
}
