// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Goal is the predicate function for goal builders.
type Goal func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)
