// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CodeSymbol is the predicate function for codesymbol builders.
type CodeSymbol func(*sql.Selector)

// Goal is the predicate function for goal builders.
type Goal func(*sql.Selector)

// GoalEvent is the predicate function for goalevent builders.
type GoalEvent func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// MemoryNode is the predicate function for memorynode builders.
type MemoryNode func(*sql.Selector)

// Pattern is the predicate function for pattern builders.
type Pattern func(*sql.Selector)

// Workspace is the predicate function for workspace builders.
type Workspace func(*sql.Selector)
